services:
  grocy-sidecar:
    image: ghcr.io/elliotmatson/tailscale-sidecar-proxy:latest
    container_name: grocy-sidecar
    hostname: grocy
    environment:
      TAILSCALE_AUTH_KEY: ${TS_AUTHKEY_CONFIG}
      TAILSCALE_STATE_DIR: "/var/lib/tailscale"
      TAILSCALE_HOSTNAME: grocy
      TAILSCALE_SERVE_PORT: 8080
      TAILSCALE_SERVE_SOURCE_MODE: http
    volumes:
      - ${PWD}/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  frontend:
    image: "grocy/frontend:v4.2.0"
    build:
      args:
        GROCY_VERSION: v4.2.0
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-frontend
    network_mode: service:grocy-sidecar
    depends_on:
      - grocy-sidecar
      - backend
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped

  backend:
    image: "grocy/backend:v4.2.0"
    build:
      args:
        GROCY_VERSION: v4.2.0
        PLATFORM: linux/amd64
      context: .
      dockerfile: Containerfile-backend
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
      - /var/www/data/viewcache:mode=755,uid=82,gid=82,size=16m
    volumes:
      - app-db:/var/www/data
    env_file:
      - grocy.env
    restart: unless-stopped

volumes:
  app-db:
